# Generated by Django 5.0 on 2023-12-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maps_link',
            field=models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d91160.57954789397!2d26.012237353149633!3d44.437918701576166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40b1f93abf3cad4f%3A0xac0632e37c9ca628!2sBucure%C8%99ti!5e0!3m2!1sro!2sro!4v1704033346511!5m2!1sro!2sro', max_length=500),
        ),
    ]
