# Generated by Django 5.0 on 2024-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_abnegative_room_abpositive_room_anegative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='getformio_link',
            field=models.CharField(default='https://getform.io/f/1d572e0e-f9aa-4867-b9a5-aa272944480f', max_length=500),
        ),
    ]
